<template>
  <div>
    <pre>
      图片优化的方式
      500 张图片，如何实现预加载优化
      懒加载具体实现
      减少http请求的方式
      webpack如何配置大型项目
      减少回流重绘
      缩小代码体积，例如：Tree-shaking、代码压缩、代码分割、Scope-hoisting等
      减少请求数，例如：雪碧图、基础库打成一个包
      并发请求，使用cdn，突破浏览器对同一域名的TCP连接数限制，或者使用http2
      运行时加载，例如：图片懒加载，组件动态import
      缓存，例如：http缓存，dll等
    </pre>
    <pre>
      <h5>为什么v-for和v-if不建议用在一起</h5>
      v-for比v-if优先级高一些，这样每次遍历v-if将重复运行，数据数据量很大，而真正要展示的数据很少时，很消耗性能
      可以用computed过滤一遍数据，然后在进行v-for数据展示
    </pre>
  </div>
</template>